### ISSUE TITLE
List Literals

### ISSUE THREAD

**Issue by qdbplang** [qdbplang/qdbp#13]
Should qdbp have a list literal syntax? If so, what should it be? Potentially something like
```Haskell
[elem1 elem2 elem3]
```

**Comment by dghosef** [comment]
The suggested syntax leads to ambiguities because of method syntax. Instead, we could do `[[expr1 expr2 ...]]`

**Comment by dghosef** [comment]
To be honest, we could just do

`@list + a + b + c`

Obviously doesn't have to be `+`

**Comment by dghosef** [comment]
Closing and moving to stdlib discussion
