### ISSUE TITLE
Arithmetic

### ISSUE THREAD

**Issue by qdbplang** [qdbplang/qdbp#14]
Currently, qdbp uses 63 bit integer arithmetic, much like ocaml. Should we keep it? If so, should there be runtime safety checks(overflow checking, etc)? If not, should we switch to bignums? And what should we do about floats

**Comment by dghosef** [comment]
63 bit integers are by far the most performant option, especially because they can fit in a pointer so don't need to be reference counted. But they can lead to subtle bugs that would be unacceptable. So the two options are switch to GMP based bignums or have checked 63 bit arithmetic

**Comment by qdbplang** [comment]
Switched to checked 63 bit signed arithmetic
