### ISSUE TITLE
Should we keep the default `this` argument?

### ISSUE THREAD

**Issue by qdbplang** [qdbplang/qdbp#3]
Different languages have different takes on this. C has a default `this` argument, python's needs to be manually specified. The obvious advantage of having one is not needing to rewrite it every time. However, in qdbp, the default `this` can sometimes get in the way. Consider the following:
```Haskell
{
  Data[3]
  Method[
    this2 := this
    {
      ; We lose access to the original `this` because
      ; the new `this` from the current object overshadows it
      ; That is why we needed to declare `this2`
      this2 Data.
    }
  ]
}
```

When we have nested prototypes, we lose access to outer `this` values because they get shadowed.

Potential ways to avoid this problem are:

1. Have no default `this` at all
2. We could have different syntaxes for methods with and without default `this`. For example,
```haskell
{
  MethodWithoutThis[body]
  MethodWithThis[|body]
  MethodWithExplicitThis[this|body]
}
```

**Comment by dghosef** [comment]
I think having a bunch of different syntaxes and having to remember when there is default this and when there isn't is a little bit too much. So either have everything or nothing have default this. And I think if it's nothing it's too much typing. So I think we should keep default this. Also, I think we should rename this to self
