### ISSUE TITLE
Add support for linking with FFI

### ISSUE THREAD

**Issue by qdbplang** [qdbplang/qdbp#5]
qdbp's FFI support is nonexistent - a syntax has been designed but has not been implemented. We need
- Command line options/parameters to specify paths to static and dynamic libraries(and maybe header files to include?)
- Good link time error messages when functions either don't exist or there are duplicates(maybe with some resolution scheme)

**Comment by dghosef** [comment]
To be honest, we could just not have an FFI and have everything implemented in qdbp, with I/O done through channels. I think I like that idea more.
